%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.10.5

-ifndef(pt_10_pb).
-define(pt_10_pb, true).

-define(pt_10_pb_gpb_version, "4.10.5").

-ifndef('PT_10000_C2S_PB_H').
-define('PT_10000_C2S_PB_H', true).
-record(pt_10000_c2s,
        {user_id = 0            :: non_neg_integer() | undefined % = 1, 32 bits
        }).
-endif.

-ifndef('PT_10000_S2C_PB_H').
-define('PT_10000_S2C_PB_H', true).
-record(pt_10000_s2c,
        {ret = 0                :: integer() | undefined, % = 1, 32 bits
         data = undefined       :: pt_10_pb:'RoleInfo'() | undefined % = 2
        }).
-endif.

-ifndef('PT_10001_C2S_PB_H').
-define('PT_10001_C2S_PB_H', true).
-record(pt_10001_c2s,
        {
        }).
-endif.

-ifndef('PT_10001_S2C_PB_H').
-define('PT_10001_S2C_PB_H', true).
-record(pt_10001_s2c,
        {ret = 0                :: integer() | undefined, % = 1, 32 bits
         data = undefined       :: pt_10_pb:'RoleInfo'() | undefined % = 2
        }).
-endif.

-ifndef('ROLEINFO_PB_H').
-define('ROLEINFO_PB_H', true).
-record('RoleInfo',
        {user_id = 0            :: non_neg_integer() | undefined, % = 1, 32 bits
         name = <<>>            :: iodata() | undefined, % = 2
         coin = 0               :: non_neg_integer() | undefined, % = 3, 32 bits
         status = 0             :: integer() | undefined % = 4, 32 bits
        }).
-endif.

-endif.
