%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.10.5

-ifndef(user_info_pb).
-define(user_info_pb, true).

-define(user_info_pb_gpb_version, "4.10.5").

-ifndef('ROLEINFO_PB_H').
-define('ROLEINFO_PB_H', true).
-record('RoleInfo',
        {user_id = 0            :: non_neg_integer() | undefined, % = 1, 32 bits
         name = <<>>            :: iodata() | undefined, % = 2
         coin = 0               :: non_neg_integer() | undefined, % = 3, 32 bits
         status = 0             :: integer() | undefined % = 4, 32 bits
        }).
-endif.

-endif.
